INSERT INTO USERS ( ID ,NAME, EMAIL, USER_ROLE, PASSWORD) VALUES (1 ,'ADMIN', 'ADMIN@ADMIN.AD', 'ADMIN', 'ADMIN');
INSERT INTO USERS ( ID ,NAME, EMAIL, USER_ROLE, PASSWORD) VALUES (2 ,'Garry', 'OPERATOR@OPERATOR.OP', 'ADOPS', '1');
INSERT INTO USERS ( ID ,NAME, EMAIL, USER_ROLE, PASSWORD) VALUES (3 ,'Fill', 'PUBLISHER@PUBLISHER.PU', 'PUBLISHER','1');

