INSERT INTO USERS ( ID ,NAME, EMAIL, USER_ROLE, PASSWORD) VALUES (1 ,'ADMIN', 'ADMIN@ADMIN.AD', 'ADMIN', 'ADMIN');
INSERT INTO USERS ( ID ,NAME, EMAIL, USER_ROLE, PASSWORD) VALUES (2 ,'OPERATOR', 'OPERATOR@OPERATOR.OP', 'ADOPS', 'OPERATOR');
INSERT INTO USERS ( ID ,NAME, EMAIL, USER_ROLE, PASSWORD) VALUES (3 ,'PUBLISHER', 'PUBLISHER@PUBLISHER.PU', 'PUBLISHER','1');
INSERT INTO USERS ( ID ,NAME, EMAIL, USER_ROLE, PASSWORD) VALUES (4 ,'PUBLISHER1', 'PUBLISHER@PUBLISHER.PU', 'PUBLISHER','1');
INSERT INTO USERS ( ID ,NAME, EMAIL, USER_ROLE, PASSWORD) VALUES (5 ,'PUBLISHER2', 'PUBLISHER@PUBLISHER.PU', 'PUBLISHER','1');

-- INSERT INTO APPS (ID, NAME, TYPE, CONTENT_TYPE, USER) VALUES (1, 'APP1', 'IOS', 'IMAGE', 1);




-- INSERT INTO TRANSACTIONS (ID, TRANSACTION_DATE, AMOUNT, CREDIT_CARD_ID) VALUES (2, '2016-01-01', 10, '1234-1234-1234-0002');
-- INSERT INTO TRANSACTIONS (ID, TRANSACTION_DATE, AMOUNT, CREDIT_CARD_ID) VALUES (3, '2016-01-02', 10, '1234-1234-1234-0002');
-- INSERT INTO TRANSACTIONS (ID, TRANSACTION_DATE, AMOUNT, CREDIT_CARD_ID) VALUES (4, '2016-01-03',  5, '1234-1234-1234-0002');